version: 2 

models:
    - name: user_stitching
      description: Each row represents a page view 
      columns:
        - name: customer_visitor_id,
          description: The customer_id for visits associated with that customer
          tests: 
            - not_null