version: 2

sources:
  - name: coffee_shop
    description: 'data about coffee roasting business'
    project: analytics-engineers-club
    freshness:
      warn_after:
        count: 398
        period: day
    loaded_at_field: created_at
    tables:
      - name: customers
        description: 'customers information from sales system'
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: orders
        description: 'orders information from sales system'
        columns:
          - name: id
            tests:
              - unique
              - not_null
  # try adding sources to the sources.yml file from last week?            
  - name: github
    database: analytics-engineers-club
    tables:
      - name: pull_request
        columns:
          - name: id
            description: "This is **not** the pull request number"
            tests:
              - unique
              - not_null

      - name: issue
        description: "This table contains issues AND pull requests"
        columns:
          - name: id
            tests:
              - unique
              - not_null
      
      - name: issue_merged
        columns:
          - name: issue_id
            tests:
              - unique
              - not_null
      - name: repository
        columns:
          - name: id
            tests:
              - unique
              - not_null